name: Deploy Pipeline Service

on:
  push:
    branches:
      - master
    paths:
      - 'src/serve/**'
      - '.github/workflows/service-ci-cd.yml'
      - 'Dockerfile'
  pull_request:
    branches:
      - master
    paths:
      - 'src/serve/**'
      - '.github/workflows/service-ci-cd.yml'
      - 'Dockerfile'

env:
  DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
  MONGO_URI: ${{ secrets.MONGO_URI }}
  GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
  GMAIL: ${{ secrets.GMAIL }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Prerequisites
        run: |
          python -m pip install --upgrade pip
          pip install  poetry

      - name: Install dependencies
        run: |
          poetry install --with dev --without win-dev


      - name: Install Railway CLI
        run: bash <(curl -fsSL cli.new)

      - name: Deploy to Railway
        run: railway up --service api
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}